@echo off
echo Starting Shodh-a-Code Backend...
cd backend
echo Building Docker image for code execution...
docker build -t shodh-a-code-judge:latest .
echo Starting Spring Boot application...
mvnw.cmd spring-boot:run
pause
